DENOPTIM: denoptim.graph.FragmentIsomorphismInspector Class Reference
denoptim.graph.FragmentIsomorphismInspector Class Reference
Public Member Functions
FragmentIsomorphismInspector (Fragment fragA, Fragment fragB)
boolean isomorphismExists ()
Iterator< GraphMapping< FragIsomorphNode, FragIsomorphEdge > > getMappings ()
Package Attributes
VF2GraphIsomorphismInspector< FragIsomorphNode, FragIsomorphEdge > vf2
Implementation of the Vento-Foggia 2 algorithm.
Detailed Description
Inspector for isomorphism on fragments. The graph representation considered is one where both atoms and AttachmentPoints are represented as graph nodes, and edges are either bonds or atom-to-attachment point connections.
Effectively, this class considers the composition and connectivity (including that of AttachmentPoints when comparing the fragments. Geometry and stereochemistry are not considered.
This call works with the VF2GraphIsomorphismInspector, see the dedicated documentation for information of patologial cases.
Author
Marco Foscato
Definition at line 22 of file FragmentIsomorphismInspector.java.
Constructor & Destructor Documentation
FragmentIsomorphismInspector()
denoptim.graph.FragmentIsomorphismInspector.FragmentIsomorphismInspector (Fragment fragA, Fragment fragB)
Definition at line 31 of file FragmentIsomorphismInspector.java.
References denoptim.graph.Fragment.getJGraphFragIsomorphism(), denoptim.graph.FragIsomorphEdge.label, denoptim.graph.FragIsomorphNode.label, and denoptim.graph.FragmentIsomorphismInspector.vf2.
Member Function Documentation
getMappings()
Iterator< GraphMapping< FragIsomorphNode, FragIsomorphEdge > > denoptim.graph.FragmentIsomorphismInspector.getMappings ()
Definition at line 65 of file FragmentIsomorphismInspector.java.
References denoptim.graph.FragmentIsomorphismInspector.vf2.
Referenced by denoptim.fragmenter.FragmentAlignement.FragmentAlignement().
isomorphismExists()
boolean denoptim.graph.FragmentIsomorphismInspector.isomorphismExists ()
Definition at line 58 of file FragmentIsomorphismInspector.java.
References denoptim.graph.FragmentIsomorphismInspector.vf2.
Referenced by denoptim.fragmenter.FragmentAlignement.FragmentAlignement(), and denoptim.graph.Fragment.isIsomorphicTo().
Member Data Documentation
vf2
VF2GraphIsomorphismInspector<FragIsomorphNode, FragIsomorphEdge> denoptim.graph.FragmentIsomorphismInspector.vf2 package
Implementation of the Vento-Foggia 2 algorithm.
Definition at line 27 of file FragmentIsomorphismInspector.java.
Referenced by denoptim.graph.FragmentIsomorphismInspector.FragmentIsomorphismInspector(), denoptim.graph.FragmentIsomorphismInspector.getMappings(), and denoptim.graph.FragmentIsomorphismInspector.isomorphismExists().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/graph/FragmentIsomorphismInspector.java