DENOPTIM: denoptim.graph.rings.CyclicGraphHandler.RingSizeManager Class Reference
denoptim.graph.rings.CyclicGraphHandler.RingSizeManager Class Reference
Utility class to calculate and manage the alternative ring sizes achievable by formation of DENOPTIMRings.
Public Member Functions
RingSizeManager (FragmentSpace fragSpace)
void initialize (IAtomContainer origMol, DGraph graph) throws DENOPTIMException
ArrayList< Vertex > getRSBiasedListOfCandidates ()
ArrayList< Vertex > getRSBiasedListOfCandidates (Vertex vI)
void addRingClosingBond (Vertex vI, Vertex vJ) throws DENOPTIMException
void setVertexAsDone (Vertex v)
boolean getCompatibilityOfPair (Vertex vI, Vertex vJ)
Private Member Functions
void fillTopologicalMatrix ()
void calculateCompatibilityOfAllRCAPairs () throws DENOPTIMException
Private Attributes
IAtomContainer mol
int[][] topoMat
ArrayList< Vertex > lstVert
int sz
Size of the list of available RCAs.
boolean[][] compatibilityOfPairs
ArrayList< Double > weigths
List of weight factors used to control the likeliness of choosing rings of a given size for the current system.
ArrayList< Boolean > done
List of flags defining if an RCA has been "used", i.e., not used to make an actual chord, but used to make a plan to make a chord and update the molecular representation accordingly.
Map< Vertex, ArrayList< Integer > > vIdToAtmId
ArrayList< Integer > ringSizeBias = settings.getRingSizeBias()
FragmentSpace fragSpace = null
Definition of the fragment space.
Detailed Description
Utility class to calculate and manage the alternative ring sizes achievable by formation of DENOPTIMRings.
Definition at line 837 of file CyclicGraphHandler.java.
Constructor & Destructor Documentation
RingSizeManager()
denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.RingSizeManager (FragmentSpace fragSpace)
Definition at line 884 of file CyclicGraphHandler.java.
References denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.fragSpace.
Member Function Documentation
addRingClosingBond()
void denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.addRingClosingBond (Vertex vI, Vertex vJ) throws DENOPTIMException
Definition at line 1144 of file CyclicGraphHandler.java.
References denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.calculateCompatibilityOfAllRCAPairs(), denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.fillTopologicalMatrix(), denoptim.graph.Edge.BondType.getCDKOrder(), denoptim.graph.Edge.BondType.hasCDKAnalogue(), denoptim.graph.rings.CyclicGraphHandler.logger, denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.mol, and denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.vIdToAtmId.
Referenced by denoptim.graph.rings.CyclicGraphHandler.getRandomCombinationOfRings().
calculateCompatibilityOfAllRCAPairs()
void denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.calculateCompatibilityOfAllRCAPairs () throws DENOPTIMException private
Definition at line 961 of file CyclicGraphHandler.java.
References denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.compatibilityOfPairs, denoptim.graph.rings.CyclicGraphHandler.evaluateRCVPair(), denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.fragSpace, denoptim.graph.rings.RingClosureParameters.getMaxRingSize(), denoptim.graph.rings.RingClosingAttractor.isAttractor(), denoptim.graph.rings.RingClosingAttractor.isCompatible(), denoptim.graph.rings.CyclicGraphHandler.logger, denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.lstVert, denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.mol, denoptim.graph.rings.CyclicGraphHandler.NL, denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.ringSizeBias, denoptim.graph.rings.CyclicGraphHandler.settings, denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.sz, denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.topoMat, denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.vIdToAtmId, and denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.weigths.
Referenced by denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.addRingClosingBond(), and denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.initialize().
fillTopologicalMatrix()
void denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.fillTopologicalMatrix () private
Definition at line 929 of file CyclicGraphHandler.java.
References denoptim.graph.rings.CyclicGraphHandler.logger, denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.mol, denoptim.graph.rings.CyclicGraphHandler.NL, and denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.topoMat.
Referenced by denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.addRingClosingBond(), and denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.initialize().
getCompatibilityOfPair()
boolean denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.getCompatibilityOfPair (Vertex vI, Vertex vJ)
Definition at line 1194 of file CyclicGraphHandler.java.
References denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.compatibilityOfPairs, and denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.lstVert.
Referenced by denoptim.graph.rings.CyclicGraphHandler.getPossibleCombinationOfRings().
getRSBiasedListOfCandidates() [1/2]
ArrayList< Vertex > denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.getRSBiasedListOfCandidates ()
Definition at line 1068 of file CyclicGraphHandler.java.
References denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.done, denoptim.graph.rings.CyclicGraphHandler.logger, denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.lstVert, denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.sz, and denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.weigths.
Referenced by denoptim.graph.rings.CyclicGraphHandler.getRandomCombinationOfRings().
getRSBiasedListOfCandidates() [2/2]
ArrayList< Vertex > denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.getRSBiasedListOfCandidates (Vertex vI)
Definition at line 1091 of file CyclicGraphHandler.java.
References denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.compatibilityOfPairs, denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.done, denoptim.graph.rings.RingClosureParameters.getMaxRingSize(), denoptim.graph.rings.CyclicGraphHandler.logger, denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.lstVert, denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.ringSizeBias, denoptim.graph.rings.CyclicGraphHandler.settings, denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.sz, denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.topoMat, and denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.vIdToAtmId.
initialize()
void denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.initialize (IAtomContainer origMol, DGraph graph) throws DENOPTIMException
Definition at line 891 of file CyclicGraphHandler.java.
References denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.calculateCompatibilityOfAllRCAPairs(), denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.done, denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.fillTopologicalMatrix(), denoptim.utils.MoleculeUtils.getVertexToAtomIdMap(), denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.lstVert, denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.mol, denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.sz, and denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.vIdToAtmId.
Referenced by denoptim.graph.rings.CyclicGraphHandler.getPossibleCombinationOfRings(), and denoptim.graph.rings.CyclicGraphHandler.getRandomCombinationOfRings().
setVertexAsDone()
void denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.setVertexAsDone (Vertex v)
Definition at line 1187 of file CyclicGraphHandler.java.
References denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.done, and denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.lstVert.
Referenced by denoptim.graph.rings.CyclicGraphHandler.getRandomCombinationOfRings().
Member Data Documentation
compatibilityOfPairs
boolean [][] denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.compatibilityOfPairs private
Definition at line 856 of file CyclicGraphHandler.java.
Referenced by denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.calculateCompatibilityOfAllRCAPairs(), denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.getCompatibilityOfPair(), and denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.getRSBiasedListOfCandidates().
done
ArrayList<Boolean> denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.done private
List of flags defining if an RCA has been "used", i.e., not used to make an actual chord, but used to make a plan to make a chord and update the molecular representation accordingly.
Definition at line 869 of file CyclicGraphHandler.java.
Referenced by denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.getRSBiasedListOfCandidates(), denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.initialize(), and denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.setVertexAsDone().
fragSpace
FragmentSpace denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.fragSpace = null private
Definition of the fragment space.
Definition at line 880 of file CyclicGraphHandler.java.
Referenced by denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.calculateCompatibilityOfAllRCAPairs(), and denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.RingSizeManager().
lstVert
ArrayList<Vertex> denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.lstVert private
Definition at line 848 of file CyclicGraphHandler.java.
Referenced by denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.calculateCompatibilityOfAllRCAPairs(), denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.getCompatibilityOfPair(), denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.getRSBiasedListOfCandidates(), denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.initialize(), and denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.setVertexAsDone().
mol
IAtomContainer denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.mol private
Definition at line 840 of file CyclicGraphHandler.java.
Referenced by denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.addRingClosingBond(), denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.calculateCompatibilityOfAllRCAPairs(), denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.fillTopologicalMatrix(), and denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.initialize().
ringSizeBias
ArrayList<Integer> denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.ringSizeBias = settings.getRingSizeBias() private
Definition at line 875 of file CyclicGraphHandler.java.
Referenced by denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.calculateCompatibilityOfAllRCAPairs(), and denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.getRSBiasedListOfCandidates().
sz
int denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.sz private
Size of the list of available RCAs.
Definition at line 853 of file CyclicGraphHandler.java.
Referenced by denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.calculateCompatibilityOfAllRCAPairs(), denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.getRSBiasedListOfCandidates(), and denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.initialize().
topoMat
int [][] denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.topoMat private
Definition at line 844 of file CyclicGraphHandler.java.
Referenced by denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.calculateCompatibilityOfAllRCAPairs(), denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.fillTopologicalMatrix(), and denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.getRSBiasedListOfCandidates().
vIdToAtmId
Map<Vertex,ArrayList<Integer> > denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.vIdToAtmId private
Definition at line 872 of file CyclicGraphHandler.java.
Referenced by denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.addRingClosingBond(), denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.calculateCompatibilityOfAllRCAPairs(), denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.getRSBiasedListOfCandidates(), and denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.initialize().
weigths
ArrayList<Double> denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.weigths private
List of weight factors used to control the likeliness of choosing rings of a given size for the current system.
Definition at line 862 of file CyclicGraphHandler.java.
Referenced by denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.calculateCompatibilityOfAllRCAPairs(), and denoptim.graph.rings.CyclicGraphHandler.RingSizeManager.getRSBiasedListOfCandidates().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/graph/rings/CyclicGraphHandler.java